name: extra_pedantic
description: Stricter Dart analyzer settings and best practices.
version: 1.3.0
author: Modestas Valauskas <valauskasmodestas+dartpub@gmail.com>
homepage: https://github.com/modulovalue/extra_pedantic
repository: https://github.com/modulovalue/extra_pedantic
issue_tracker: https://github.com/modulovalue/extra_pedantic/issues

environment:
  sdk: '>=2.12.0-0.beta <3.0.0'
